#!/bin/bash

white_list=.*login,.*register,location/lang

mongo_url=localhost

p=$0
p=${p%/*}
p=${p:1}
p="$PWD"$p

java -Duser.dir=$p -Dmongo.urls=$mongo_url -jar -DwhiteList=$white_list $p/maxleap-baas-apiserver-1.0.0-fat.jar